name: Percy
on: [push, pull-request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        with:
          build-directory: "_public/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}